### ISSUE TITLE
Server disappears from (or does not appear in) lobby

### ISSUE THREAD

**Issue by kiview** [assetto-corsa-web/accweb#100]
I have set up a server instance on Oracle cloud on a Ubuntu 20.04 image.
Sometimes the server only appears after a long time in the lobby or disappears. Restarting a server often solves the problem. A little bit lost right now how to debug it (besides diving into tcpdump). I have opened the corresponding ports in iptables and in my cloud firewall.

Are there maybe some problems with regards to NATing in Docker? Are folks running accweb using the Docker image in production?

My compose is as follows (for final deployment, I was planning to put traefik as SSL reverse proxy in from of the HTTP port):

```
version: '3'

services:
  accweb:
    image: kugel/accweb:latest
    container_name : accweb-server
    restart: always
    ports:
      - 80:8080
      - 2600:2600
      - 2600:2600/udp
      - 2601:2601
      - 2601:2601/udp
    volumes:
      - "accweb:/accweb"
      - "acccerts:/sslcerts"
      - "./accserver:/accserver"
    environment:
      ACCWEB_HOST: 0.0.0.0:8080
      ACCWEB_ENABLE_TLS: "false"
      ACCWEB_CERT_FILE: /sslcerts/certificate.crt
      ACCWEB_PRIV_FILE: /sslcerts/private.key
      ACCWEB_LOGLEVEL: debug
      ACCWEB_CORS: "*"
    networks:
      - accnetwork

networks:
  accnetwork:

volumes:
  accweb:
  acccerts:
  accserver:

```
